language: cpp
dist: xenial
os: linux
compiler: gcc
addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - cmake 
      - g++-8
      - binutils-gold
env:
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"        
   

before_install:
  - eval "${MATRIX_EVAL}"

jobs:
  include: 
    - stage: cmake-config
      script:
       - cmake --version
       - mkdir llvm/build && cd llvm/build
       - cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_LINKER=gold -DLLVM_ENABLE_PROJECTS="clang-tools-extra" -DLLVM_PARALLEL_LINK_JOBS=1 ..
    - stage: llvmcore
      script:
       - cmake --build . --config Release --target LLVMCore -- -j $(nproc)
    - stage: lto
      script:
       - cmake --build . --config Release --target LTO -- -j $(nproc)
    - stage: rest
      script:
       - cmake --build . --config Release -- -j $(nproc)

stages:
 - cmake-config
 - llvmcore
 - lto
 - rest